//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#include <RTOS_CGlobals.h>
#include <RTOS_CMacros.h>
#include "C_types.h"
#include "C_channels.h"
