//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#pragma once
#define __LSLPRJ_UNITS_H__

//Acceleration
#define  mmPsec2	*1

//Angle
#define  deg	*10000

//Area
#define  mm2	*10	//x.x sqare millimeter

//Force
#define  kN	*1000 N
#define  N	*1

//Length
#define  m	*1000 mm
#define  mm	*10000

//Memory
#define  GB	*1024 MB
#define  kB	*1024
#define  MB	*1024 kB

//Pressure
#define  bar	*1000	//x.xxx Bar ( MilliBar)

//Revolution
#define  RPM	*1000

//Speed
#define  mlpmin	*1
#define  mmpsec	*10000

//Time
#define  hours	*60 min
#define  min	*60 secs
#define  ms	*1
#define  sec	*1000
#define  secs	*1000 ms

//Volume
#define  ccm	*1	//cubic centimeter
